### ISSUE TITLE
Submit to Colorsublime?

### ISSUE THREAD

**Issue by JulianNorton** [saadq/Material-Spacegray#1]
https://github.com/Colorsublime/Colorsublime-Themes

**Comment by saadq** [comment]
I'm pretty sure Colorsublime is meant only for color schemes and not themes (I've actually submitted a few color schemes to them in the past). And since Material Spacegray is mostly a theme modification that uses the base16-ocean color scheme from Spacegray, it wouldn't really make much sense to submit it. Thanks for the suggestion.
